### ISSUE TITLE
Is it possible to briefly describe how "Database Observation" work behind the scene? 

### ISSUE THREAD

**Issue by yccheok** [groue/GRDBCombine#12]
I believe achieving "Database Observation" is a rather complex task, as we need to notify correct table's observers, after executing the SQL statement.

Is it possible to briefly describe the working mechanism of "Database Observation"? Is it

1. Rely on some "built-in" features provided by SQLite, out of the box?
2. Base on smart algorithm code developed in "GRDBCombine"?
3. ...

So that as lib user, we can have a big picture on how it works, and aware of possible limitation.

Just FYI, this is the information, on how Android's Room LiveData works - https://www.reddit.com/r/androiddev/comments/clm1pd/does_anyone_how_the_magic_works_for_rooms_livedata/

Thanks.

**Comment by groue** [comment]
Hello @yccheok,

GRDB database observation relies on built-in features of SQLite:

- [Commit And Rollback Notification Callbacks](https://www.sqlite.org/c3ref/commit_hook.html)
- [Data Change Notification Callbacks](https://www.sqlite.org/c3ref/update_hook.html)
- [Compile-Time Authorization Callbacks](https://www.sqlite.org/c3ref/set_authorizer.html)

On this base, GRBD can define the [TransactionObserver](https://github.com/groue/GRDB.swift/blob/master/README.md#transactionobserver-protocol) protocol, which is the mother of all GRDB observation features. TransactionObserver is supported by the inner type DatabaseObservationBroker. You can read a brief description of how it works at https://github.com/groue/GRDB.swift/blob/v4.2.0/GRDB/Core/TransactionObserver.swift#L83

On top of TransactionObserver, GRDB defines all its [Database Observation](https://github.com/groue/GRDB.swift/blob/master/README.md#database-changes-observation) features.

Among those, you have [ValueObservation](https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservation). GRDBCombine is just a thin wrapper around it.

> So that as lib user, we can have a big picture on how it works, and aware of possible limitation.

"possible limitation" is quite vague because nobody knows what you want to do. I hope the information linked above will give you the answer you look for.
