### ISSUE TITLE
Support of Cocoapods

### ISSUE THREAD

**Issue by benrudhart** [groue/GRDBCombine#28]
Hi there,
is support for CocoaPods planned for GRDBCombine?

**Comment by groue** [comment]
Hello @benrudhart,

It is not planned by *me*, but you can: pull requests are welcome!

**Comment by pocketpixels** [comment]
Would this likely just involve writing the Podspec file? 
I haven't created a Cocoapod before, but am also interested in this, because I wrote a SwiftUI app using GRCBCombine, and when adding a WatchKit extension am blocked by [this issue with the Swift Package Manager](https://github.com/groue/GRDB.swift/issues/642).
I am hoping that I could work around this by switching all my packages over to CocoaPods.

**Comment by groue** [comment]
You need **education** about how free open-source projects work, so that you never write such a rude comment again. Nobody owes you anything, maybe someone will "just" write the podspec for you, and that's not me because I'm enjoying well deserved vacations where my involvement is as high as the probability of your comment to have any effect.

**Comment by pocketpixels** [comment]
Whoa, I am very sorry my comment offended you. That was not at all intended. 
What my question was about is what would be involved in adding support for CocoaPods, and whether it is something that I could likely tackle without prior experience. 
In fact I was in the process of writing an initial Podspec file right now, though I don't know if that is all that will be necessary or if other changes to the repo structure and/or code will be necessary.

**Comment by pocketpixels** [comment]
Anyway, I will see if I can get it to work locally by writing a Podspec file, and if yes I will submit a pull request with the draft Podspec file

**Comment by groue** [comment]
That's a much better strategy, thank you.

**Comment by pocketpixels** [comment]
That was my strategy all along (though I agree I didn't express it very clearly). 
My question was intended as "Would this be easy/feasible for me to do?", rather than "Wouldn't this be easy for you to add? Why don't you?"

**Comment by groue** [comment]
👍 I'm happy there is no misunderstanding left.
