### ISSUE TITLE
Package dependency graph build error

### ISSUE THREAD

**Issue by haikusw** [groue/GRDBCombine#32]
(PR prepared)

The package dependency graph can not be resolved, possibly because of these requirements:

https://github.com/groue/GRDB.swift.git — 4.1.0..<5.0.0
https://github.com/groue/CombineExpectations.git — 0.3.0..<1.0.0
https://github.com/groue/CombineExpectations.git — 0.2.0
https://github.com/groue/GRDB.swift — 4.1.0..<5.0.0

**Comment by groue** [comment]
Indeed the demo app won't build. Thanks for spotting this bug! I'm closing this issue in favor of #33.

**Comment by haikusw** [comment]
Sounds good.  I wasn't sure if you wanted pull requests to be associated with issues like some repos do; that's why I wrote one to go with the PR.  I will just do PRs in the future.

**Comment by groue** [comment]
What I want to avoid is to discourage a contributor because I have to discard an ill-advised pull request. Opening issues first is usually a good way to avoid such frustration, because both maintainer and contributor spend only useful time, which leads on an agreement that a pull request is needed, or not. This is especially true for "big" or "controversial" topics.

In the particular case of #32 and #33, the topic is small, issue and the pull request are nearly identical, and we're about to find an agreement. So we can do without much ceremony.

But please don't generalize from this particular case, will you? ;-)

**Comment by haikusw** [comment]
Understood. Makes sense. Thank you.
